apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: fitness-deployment 
  labels:
    first: app 
spec:
  replicas: 1             #or try putting 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web 
    spec: 
      containers:
        - name: fitness-cont 
          image: mpriyakirana14/fitness-tracker:v1.0.0
          ports: 
            - containerPort: 5000