apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name:  cartify-zepto
      image: priyakirana14/zepto-app-web:v5.1.0
      ports:
        -  containerPort: 80

    - name: vegetable-cont
      image: priyakirana14/vegetables:v1.0.0
      ports:
        -  containerPort: 3000

    - name: flipkart-cont
      image: priyakirana14/newflipkart:v1.0.0
      ports:
       -  containerPort: 80