apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: zepto-app-rs
  labels:
    app: web
spec: # Defines the Behaviour of the replicaset 
  replicas: 3 
  selector:
    matchLabels:
      web: zepto
  template:
    metadata:
      labels:
        web: zepto 
    spec: # Defines the Behaviour of the Pod 
      containers:
        - image: priyakirana14/zepto-app-web:v5.1.0
          name: zepto-web-cont
          ports:
            - containerPort: 80