
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zepto-app-rs
spec: #Defines the behaviour of replicaset
  replicas: 3
  selector:    #specify how to identify the pods that belong to this replicaset
    matchLabels:
      web: zepto
template: 
  metadata:
    labels:      #it is belonging to pod template
      web: zepto
  spec: #Defines the behaviour of pod
    containers:
      - image: priyakirana14/zepto-app-web:v5.1.0
        name: zepto-cont
        ports:
          - containerPort: 3015